language: node_js
node_js:
- '0.12'
branches:
  only:
  - source
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo generate
after_success:
- git config --global user.name "Molly Stark"
- git config --global user.email "menglei0318@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy --silent
env:
  global:
    secure: Xka8Qu+c0OzWZp+cw/4XCrqyAm8IShPf+xFXiAo5hJAII0iqCfbNXo+4z8PPoG/lXGMjipeccqThGyY5K6dIgJ0oqDjj1wRk5VJ5au4cneLBH7t2HhC9T0nAodwZrmuDAQjYlNtty1pM3X9PRmcQDTaDGkAJI57V0/Yv6KFDwpH2t5TkrBiuFeYJA4SjupvHbvZYuzXi7chWac3SkTtbsH4uKh+erVevJ1pipY0BYodiM5aZftc6Vde2mYhsEH4ViE96h3i/NNqSBR6MOfEn/FWMuUrtRHIaU1CcuJN9TEdabls2XsejwCpkSLuNQamITqcAoTrZaGxTOMIMHeNOXWg26BSDowUtG6jHquQe6JvCB72A7Yq+NIjWvkbaNfM5gV38nwJx3XmdYJpJMee3DEoya+bS6VpwIUfwQPpOr3H9I/FdS3v2peCkpNFvXpjKZXDhwrGiztyFNKhm1oMRdAsJDJ+nVVHfAKuPT4UbMqco0ANg0L4uAL1laTucpQFMlOAHcCWk9SBQy5ti98nkeSKAdpQDj8Bi1AmKr3yO81pLNyYl9Gj4nYxqNaGOIG9Skfftt5nqAc21ENF6gIQzStgeHHOgDFEN2/j+s555MzND2nDYdAKod1fE4/oSkGttcaIq84okVqBS8gp4OcYLt7cDd94PXllxbVWs6DGeEZY=
