language: node_js
node_js:
- 6.0.0
branches:
  only:
  - source
before_install:
- npm install -g hexo-cli@1.0.3
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo generate
after_success:
- git config --global user.name "Molly Stark"
- git config --global user.email "menglei0318@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
env:
  global:
    secure: RFeIZkOoiLOsksjnplI5+mju3j1t9ad7Sv+edP3De1xN4OIxeC0E0a05EBT7U60ikjJOPnDEazD1k8FRKCvagPAJk+CP1VHMwMHkDSdmlCCh6YbVRQjeTGqrW3j+1FEPR05hiELJOmNXLHze2/PCBA7SyTw7t0ydE9K7LGkm0MQA5NvjJULgtzoUzbBlfzYQC572tvcOXYtfMe3Sn+CgcvOJbzCkgqkYIzcJlWtsca5U2Jo+Bl4lEIx+b//vsPmX1dBsghNkJogMEZ0Pk3KkGZjdixicxOc3p58Zd+Xemty4hLDRotzY3XZnHVynaXYQWxhMRgED0hxG0EhqIqPXKYmHc4oI1D49zGkRlNWNPidQnE0gcB9/kNbYoHctZR+4eyVWr0Nfi/XhREzC7s2EuRMQBDAQ7/mtgGs8mBkt7aqeyrI0fWjDRbXRLQArBVEpZbGLTLlJfZtyELTWTsWcheOTKtmKllxUHz6ZOZQxeKyzjPRzSTcHM7nZSLhhAhaNf3EumPJonj9Eri5a5IDv2e3lrGPD2xkBrtXuWAeXxm1xaqRirtYh6lmoDq7Fj7d3zpoAGXiUGwYQCe/jC5b8EOFpH2Iv1Xootzrw2+CcpEKTcSzakiEl6T0SlwqcPhOGUsePW+nfKzbXpPNH2gsnMCqJ9M5rIdIGI8B9omqN9r4=
